import os
import platform
import random
print ("Hello world!")
print("This project is in beta v2.0")
print("This project was created by mraz0tix-code")
print("I love PYTHON!\n" + "="*30)
name = input("Hello! What is your name? -> ")
print(f"Nice to meet you, {name}!")
current_os = platform.system()
print(f"I detected that your operating system is: {current_os}. Great choice!")
like_linux = input("Do you like Linux? (yes/no) -> ").lower().strip()
if like_linux in ["yes", "y", "да"]:
    print("Awesome! Penguins rule the world! 🐧")
elif like_linux in ["no", "n", "нет"]:
    print(f"That's fine, {current_os} is still a solid system.")
else:
    print("Interesting answer!")
facts = [
    "Python was named after the comedy television show 'Monty Python's Flying Circus'.",
    "Python is older than Java! It was first released in 1991.",
    "Python is the most popular language for Machine Learning and AI."
    "This is project created russian person.",
    "About 30 percent of internet traffic is generated by bots, not humans."
    ]
print("\n" + "="*30)
print("Here is a random Python fact for you:")
print(random.choice(facts)) 
print("\nThank you for trying this beta!")
print ("Bye, bye, bye world!")